### ISSUE TITLE
Failed to execute script setup error

### ISSUE THREAD

**Issue by Lowide** [Pavithran-07/Automated_online_class_tool#1]
![WhatsApp Image 2020-11-19 at 10 53 46 AM](https://user-images.githubusercontent.com/74721417/99677020-025bee80-2a58-11eb-8038-39cd43ce9d2b.jpeg)
When I try to open the setup.exe file this error happens, and the error happens even with the code downloaded from github.

**Comment by Pavithran-07** [comment]
I think you left the image or something else in which the exe is dependent. Please try to add the image to the same directory where the exe is located. Let me know if that solves.

**Comment by Lowide** [comment]
nope, the image and the program are on the same directory and the same error again, I've tried running it on cmd, and it says 
```
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from mainv2 import CRUD,totalInput
ModuleNotFoundError: No module named 'mainv2'

```
And when I try installing "mainv2" with`pip install mainv2` it gives this error:
```
ERROR: Could not find a version that satisfies the requirement mainv2 (from versions: none)
ERROR: No matching distribution found for mainv2
```
also thx for responding so fast!

**Comment by Pavithran-07** [comment]
Yeah! Sorry for the error. I haven’t noticed this change your main.py to mainv2.py. I think this will clear the error. Try this and lemme know.

**Comment by Lowide** [comment]
It works! thx!
